name: flutter_login_mobx_multi_theming
description: flutter_login_mobx_multi_theming.
version: 1.0.0+1

publish_to: none

environment:
  sdk: ^2.19.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  mobx: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
